controller_manager:
  ros__parameters:
    update_rate: 50  # Hz (reduced from 100 Hz for better compatibility)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg1_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg2_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg3_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    leg4_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    leg5_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    leg6_controller:
      type: joint_trajectory_controller/JointTrajectoryController

leg1_controller:
  ros__parameters:
    joints:
      - joint_1_1
      - joint_1_2
      - joint_1_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

leg2_controller:
  ros__parameters:
    joints:
      - joint_2_1
      - joint_2_2
      - joint_2_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

leg3_controller:
  ros__parameters:
    joints:
      - joint_3_1
      - joint_3_2
      - joint_3_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

leg4_controller:
  ros__parameters:
    joints:
      - joint_4_1
      - joint_4_2
      - joint_4_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

leg5_controller:
  ros__parameters:
    joints:
      - joint_5_1
      - joint_5_2
      - joint_5_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

leg6_controller:
  ros__parameters:
    joints:
      - joint_6_1
      - joint_6_2
      - joint_6_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true